In [ ]:
# Importing libraries
# Also uploading file

import pandas as pd
import numpy as np

In [ ]:
# Assigning file an easy name

industry = pd.read_csv('industryAnalysis_2000_2022.csv')

In [ ]:
# Displaying file

display(industry)

,gvkey,datadate,fyear,indfmt,consol,popsrc,datafmt,tic,conm,curcd,...,at,cogs,csho,emp,ib,oibdp,sale,costat,prcc_c,naics
0,1004,20010531,2000.0,INDL,C,D,STD,AIR,AAR CORP,USD,...,701.854,713.811,26.937,2.500,18.531,64.367,874.255,A,12.625,423860.0
1,1004,20020531,2001.0,INDL,C,D,STD,AIR,AAR CORP,USD,...,710.199,526.477,31.870,2.200,-58.939,27.207,638.721,A,9.010,423860.0
2,1004,20030531,2002.0,INDL,C,D,STD,AIR,AAR CORP,USD,...,686.621,496.747,31.851,2.100,-12.410,30.745,606.337,A,5.150,423860.0
3,1004,20040531,2003.0,INDL,C,D,STD,AIR,AAR CORP,USD,...,709.292,523.302,32.245,2.300,3.504,47.491,651.958,A,14.950,423860.0
4,1004,20050531,2004.0,INDL,C,D,STD,AIR,AAR CORP,USD,...,732.230,598.172,32.586,2.600,18.572,61.774,747.848,A,13.620,423860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254548,345980,20191231,2019.0,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,...,1366.000,433.000,103.695,NaN,-129.000,-134.000,1901.000,A,NaN,454110.0
254549,345980,20201231,2020.0,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,...,2397.000,935.000,587.000,0.875,-745.000,-619.000,2541.000,A,18.240,454110.0
254550,347085,20190228,2018.0,INDL,C,D,STD,KARO,KAROOOOO LTD,USD,...,108.754,17.509,0.001,NaN,16.851,55.286,120.390,A,NaN,518210.0
254551,347085,20200229,2019.0,INDL,C,D,STD,KARO,KAROOOOO LTD,USD,...,117.551,17.774,0.001,NaN,18.467,62.411,123.708,A,NaN,518210.0
254552,347085,20210228,2020.0,INDL,C,D,STD,KARO,KAROOOOO LTD,USD,...,192.079,17.904,21.383,3.122,20.965,79.334,150.924,A,NaN,518210.0

In [ ]:
# Applying filters to file for naics code 454110 and for the fiscal year 2018
# Also only keeping the needed columns

industry.loc[(industry['naics'] == 454110)&(industry['fyear'] == 2018),['tic','conm','at','naics','fyear']]

          tic                          conm          at     naics   fyear
30718     WSM           WILLIAMS-SONOMA INC    2812.844  454110.0  2018.0
33503    KSPN          KASPIEN HOLDINGS INC     138.013  454110.0  2018.0
37383   0189A                       QVC INC   14856.000  454110.0  2018.0
54693    LITB      LIGHTINTHEBOX HLDG  -ADR     103.587  454110.0  2018.0
61285      LE                LANDS' END INC    1110.911  454110.0  2018.0
61735      JD                    JD.COM INC   30411.441  454110.0  2018.0
64100    JMEI  JUMEI INTL HOLDING LTD  -ADR     747.649  454110.0  2018.0
66871    RMBL                  RUMBLEON INC     108.926  454110.0  2018.0
68352       W                   WAYFAIR INC    1890.850  454110.0  2018.0
74543    BZUN                    BAOZUN INC     583.879  454110.0  2018.0
76209    IMBI             IMEDIA BRANDS INC     229.987  454110.0  2018.0
85850    DLTH           DULUTH HOLDINGS INC     296.759  454110.0  2018.0
91135    BBRW              BREWBILT MFG INC       0.032  454110.0  2018.0
102002   NETS           NETSHOES CAYMAN LTD     256.846  454110.0  2018.0
104337   CVNA                    CARVANA CO     991.013  454110.0  2018.0
105066   NTRI               NUTRISYSTEM INC     204.237  454110.0  2018.0
106552   APRN         BLUE APRON HOLDNG INC     354.899  454110.0  2018.0
106700   PCMI                       PCM INC     720.950  454110.0  2018.0
106861  GDDFF          GOODFOOD MARKET CORP      34.309  454110.0  2018.0
108204   SECO        SECOO HOLDING LTD -ADS     551.326  454110.0  2018.0
109043   SFIX                STITCH FIX INC     481.585  454110.0  2018.0
112201   MOGU                 MOGU INC -ADR     685.960  454110.0  2018.0
112323   RVLV             REVOLVE GROUP INC     162.074  454110.0  2018.0
112472  RBZHF           REEBONZ HOLDING LTD      79.139  454110.0  2018.0
112892   RUHN        RUHNN HOLDING LTD -ADR     102.704  454110.0  2018.0
112990   JMIA        JUMIA TECHNOLOGIE -ADR     162.598  454110.0  2018.0
113040     YJ                YUNJI INC -ADR     569.772  454110.0  2018.0
113320  LKNCY        LUCKIN COFFEE INC -ADR     506.711  454110.0  2018.0
113509   CHWY                     CHEWY INC     541.622  454110.0  2018.0
114329   MOHO               ECMOHO LTD -ADS     117.772  454110.0  2018.0
114553    MKD       MOLECULAR DATA INC -ADS      54.028  454110.0  2018.0
116028    WNW  MEIWU TECHNOLOGY COMPANY LTD       1.869  454110.0  2018.0
116198   DASH                  DOORDASH INC     683.000  454110.0  2018.0
116331   POSH                  POSHMARK INC     147.399  454110.0  2018.0
116643   CPNG                   COUPANG INC         NaN  454110.0  2018.0
116733   ACVA              ACV AUCTIONS INC         NaN  454110.0  2018.0
116753   TDUP                   THREDUP INC         NaN  454110.0  2018.0
116864   GLBE           GLOBAL-E ONLINE LTD         NaN  454110.0  2018.0
117206   CURV           TORRID HOLDINGS INC         NaN  454110.0  2018.0
133107   AMZN                AMAZON.COM INC  162648.000  454110.0  2018.0
141249   CNXN             PC CONNECTION INC     805.355  454110.0  2018.0
161144   FLWS             1-800-FLOWERS.COM     570.889  454110.0  2018.0
181119   OSTK             OVERSTOCK.COM INC     461.219  454110.0  2018.0
197301  FTDCQ               GUE LIQ COS INC     386.980  454110.0  2018.0
206118   LQDT        LIQUIDITY SERVICES INC     201.832  454110.0  2018.0
207217   BGRP            BLUESTEM GROUP INC     649.359  454110.0  2018.0
208554   VIPS          VIPSHOP HOLDINGS LTD    6333.776  454110.0  2018.0
210130  QRTEA             QURATE RETAIL INC   17841.000  454110.0  2018.0
217287   PRTS              CARPARTS COM INC      97.965  454110.0  2018.0
220065    ATV  ACORN INTERNATIONAL INC -ADR      90.137  454110.0  2018.0
254547   WISH              CONTEXTLOGIC INC    1193.000  454110.0  2018.0

In [ ]:
# Assigning a name to the filtered file

naics_454110 = industry.loc[(industry['naics'] == 454110)&(industry['fyear'] == 2018),['tic','conm','at','naics','fyear']]

In [ ]:
# Seeing the assigned file to make sure it works

naics_454110

          tic                          conm          at     naics   fyear
30718     WSM           WILLIAMS-SONOMA INC    2812.844  454110.0  2018.0
33503    KSPN          KASPIEN HOLDINGS INC     138.013  454110.0  2018.0
37383   0189A                       QVC INC   14856.000  454110.0  2018.0
54693    LITB      LIGHTINTHEBOX HLDG  -ADR     103.587  454110.0  2018.0
61285      LE                LANDS' END INC    1110.911  454110.0  2018.0
61735      JD                    JD.COM INC   30411.441  454110.0  2018.0
64100    JMEI  JUMEI INTL HOLDING LTD  -ADR     747.649  454110.0  2018.0
66871    RMBL                  RUMBLEON INC     108.926  454110.0  2018.0
68352       W                   WAYFAIR INC    1890.850  454110.0  2018.0
74543    BZUN                    BAOZUN INC     583.879  454110.0  2018.0
76209    IMBI             IMEDIA BRANDS INC     229.987  454110.0  2018.0
85850    DLTH           DULUTH HOLDINGS INC     296.759  454110.0  2018.0
91135    BBRW              BREWBILT MFG INC       0.032  454110.0  2018.0
102002   NETS           NETSHOES CAYMAN LTD     256.846  454110.0  2018.0
104337   CVNA                    CARVANA CO     991.013  454110.0  2018.0
105066   NTRI               NUTRISYSTEM INC     204.237  454110.0  2018.0
106552   APRN         BLUE APRON HOLDNG INC     354.899  454110.0  2018.0
106700   PCMI                       PCM INC     720.950  454110.0  2018.0
106861  GDDFF          GOODFOOD MARKET CORP      34.309  454110.0  2018.0
108204   SECO        SECOO HOLDING LTD -ADS     551.326  454110.0  2018.0
109043   SFIX                STITCH FIX INC     481.585  454110.0  2018.0
112201   MOGU                 MOGU INC -ADR     685.960  454110.0  2018.0
112323   RVLV             REVOLVE GROUP INC     162.074  454110.0  2018.0
112472  RBZHF           REEBONZ HOLDING LTD      79.139  454110.0  2018.0
112892   RUHN        RUHNN HOLDING LTD -ADR     102.704  454110.0  2018.0
112990   JMIA        JUMIA TECHNOLOGIE -ADR     162.598  454110.0  2018.0
113040     YJ                YUNJI INC -ADR     569.772  454110.0  2018.0
113320  LKNCY        LUCKIN COFFEE INC -ADR     506.711  454110.0  2018.0
113509   CHWY                     CHEWY INC     541.622  454110.0  2018.0
114329   MOHO               ECMOHO LTD -ADS     117.772  454110.0  2018.0
114553    MKD       MOLECULAR DATA INC -ADS      54.028  454110.0  2018.0
116028    WNW  MEIWU TECHNOLOGY COMPANY LTD       1.869  454110.0  2018.0
116198   DASH                  DOORDASH INC     683.000  454110.0  2018.0
116331   POSH                  POSHMARK INC     147.399  454110.0  2018.0
116643   CPNG                   COUPANG INC         NaN  454110.0  2018.0
116733   ACVA              ACV AUCTIONS INC         NaN  454110.0  2018.0
116753   TDUP                   THREDUP INC         NaN  454110.0  2018.0
116864   GLBE           GLOBAL-E ONLINE LTD         NaN  454110.0  2018.0
117206   CURV           TORRID HOLDINGS INC         NaN  454110.0  2018.0
133107   AMZN                AMAZON.COM INC  162648.000  454110.0  2018.0
141249   CNXN             PC CONNECTION INC     805.355  454110.0  2018.0
161144   FLWS             1-800-FLOWERS.COM     570.889  454110.0  2018.0
181119   OSTK             OVERSTOCK.COM INC     461.219  454110.0  2018.0
197301  FTDCQ               GUE LIQ COS INC     386.980  454110.0  2018.0
206118   LQDT        LIQUIDITY SERVICES INC     201.832  454110.0  2018.0
207217   BGRP            BLUESTEM GROUP INC     649.359  454110.0  2018.0
208554   VIPS          VIPSHOP HOLDINGS LTD    6333.776  454110.0  2018.0
210130  QRTEA             QURATE RETAIL INC   17841.000  454110.0  2018.0
217287   PRTS              CARPARTS COM INC      97.965  454110.0  2018.0
220065    ATV  ACORN INTERNATIONAL INC -ADR      90.137  454110.0  2018.0
254547   WISH              CONTEXTLOGIC INC    1193.000  454110.0  2018.0

In [ ]:
# Using describe to find the mean of at(Total Assets) for the filtered file

naics_454110.describe()

                  at     naics   fyear
count      46.000000      51.0    51.0
mean     5477.830500  454110.0  2018.0
std     24312.446889       0.0     0.0
min         0.032000  454110.0  2018.0
25%       140.359500  454110.0  2018.0
50%       471.402000  454110.0  2018.0
75%       740.974250  454110.0  2018.0
max    162648.000000  454110.0  2018.0

In [ ]:
# Above we can see that the mean of at(Total Assets) of companies with the naics
#   code 454110 for the fyear(fiscal year) 2018 is 5477.8305